/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook.glb -T -t 
Files: macbook.glb [629.72KB] > /Users/chiro/Desktop/Escritorio/Cursos_y_estudios/youtube/trheejs/macbookprolanding/public/models/macbook-transformed.glb [627.9KB] (0%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import { useGLTF, useVideoTexture } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { useEffect, type JSX } from "react";
import { Mesh, MeshStandardMaterial, AnimationClip, Color } from "three";
import { useMacbookStore } from "../../store";
import { noChangeParts } from "../../constants";

type GLTFResult = GLTF & {
  nodes: {
    Object_10: Mesh;
    Object_16: Mesh;
    Object_20: Mesh;
    Object_22: Mesh;
    Object_30: Mesh;
    Object_32: Mesh;
    Object_34: Mesh;
    Object_38: Mesh;
    Object_42: Mesh;
    Object_48: Mesh;
    Object_54: Mesh;
    Object_58: Mesh;
    Object_66: Mesh;
    Object_74: Mesh;
    Object_82: Mesh;
    Object_96: Mesh;
    Object_107: Mesh;
    Object_123: Mesh;
    Object_127: Mesh;
  };
  materials: {
    PaletteMaterial001: MeshStandardMaterial;
    zhGRTuGrQoJflBD: MeshStandardMaterial;
    PaletteMaterial002: MeshStandardMaterial;
    lmWQsEjxpsebDlK: MeshStandardMaterial;
    LtEafgAVRolQqRw: MeshStandardMaterial;
    iyDJFXmHelnMTbD: MeshStandardMaterial;
    eJObPwhgFzvfaoZ: MeshStandardMaterial;
    nDsMUuDKliqGFdU: MeshStandardMaterial;
    CRQixVLpahJzhJc: MeshStandardMaterial;
    YYwBgwvcyZVOOAA: MeshStandardMaterial;
    SLGkCohDDelqXBu: MeshStandardMaterial;
    WnHKXHhScfUbJQi: MeshStandardMaterial;
    fNHiBfcxHUJCahl: MeshStandardMaterial;
    LpqXZqhaGCeSzdu: MeshStandardMaterial;
    gMtYExgrEUqPfln: MeshStandardMaterial;
    PaletteMaterial003: MeshStandardMaterial;
    JvMFZolVCdpPqjj: MeshStandardMaterial;
    sfCQkHOWyrsLmor: MeshStandardMaterial;
    ZCDwChwkbBfITSW: MeshStandardMaterial;
  };
  animations: AnimationClip[];
};

export function ModelMacbook(props: JSX.IntrinsicElements["group"]) {
  const { color, texture } = useMacbookStore();

  const { nodes, materials, scene } = useGLTF(
    "/models/macbook-transformed.glb",
  ) as unknown as GLTFResult;

  const screen = useVideoTexture(texture);
  
  useEffect(() => {
    scene.traverse((child) => {
      if (child instanceof Mesh) {
        if (!noChangeParts.includes(child.name)) {
          child.material.color = new Color(color);
        }
      }
    });
  }, [color, scene]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.zhGRTuGrQoJflBD}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.PaletteMaterial002}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.lmWQsEjxpsebDlK}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.LtEafgAVRolQqRw}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.iyDJFXmHelnMTbD}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.eJObPwhgFzvfaoZ}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.nDsMUuDKliqGFdU}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.CRQixVLpahJzhJc}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.YYwBgwvcyZVOOAA}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.SLGkCohDDelqXBu}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.WnHKXHhScfUbJQi}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials.fNHiBfcxHUJCahl}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.LpqXZqhaGCeSzdu}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials.gMtYExgrEUqPfln}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.PaletteMaterial003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_107.geometry}
        material={materials.JvMFZolVCdpPqjj}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Object_123.geometry} rotation={[Math.PI / 2, 0, 0]}>
        <meshBasicMaterial map={screen} />
      </mesh>
      <mesh
        geometry={nodes.Object_127.geometry}
        material={materials.ZCDwChwkbBfITSW}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/macbook-transformed.glb");
